[build]
  # Directory where Netlify installs dependencies and runs the build command
  base = ""
  # Build command to compile your React app
  command = "npm run build"
  # Directory where the build files are placed after running the build command
  publish = "build"

[[redirects]]
  # Redirect all routes to index.html to support React Router
  from = "/*"
  to = "/index.html"
  status = 200
